name: HAR 模板发布
description: 请按照提示, 发布新的 HAR 模板, 修改 HAR 模板文件请在原模板评论区进行.
title: " 评论区"
labels: ["har"]
body:
  - type: input
    id: name
    attributes:
      label: HAR 模板名称
      description: |
        请提供 HAR 文件的命名, 空格请用下划线代替, 允许中文, 请勿使用括号等特殊字符
      placeholder: "Example_HARNAME"
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: 作者信息
      description: |
        请提供 HAR 文件的作者名或昵称, 用英文逗号 `,` 分隔多个作者, 请勿使用括号等特殊字符
      placeholder: "Example_Author1, Example_Author2"
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: 模板备注及说明
      description: |
        HAR 文件的备注信息及说明, 选填
  - type: input
    id: filename
    attributes:
      label: HAR 文件名
      description: |
        请提供 HAR 文件的文件名, 含 `.har` 后缀, 允许中文, 请勿使用括号等特殊字符
      placeholder: "Example_HARNAME.har"
  - type: textarea
    id: other_information
    attributes:
      label: 其他信息
      description: |
        请提供其他信息, 例如: 对于 Issue 的其他说明, 选填, 如无请填暂无
      render: Markdown
  - type: textarea
    id: har_content
    attributes:
      label: HAR 模板内容
      description: |
        请将 HAR 文件内容粘贴到此处, 允许使用 json 格式化工具进行格式化后再粘贴
      render: JSON
