name: Update Base64 Content
on:
  workflow_dispatch: {}
  push:
    paths:
      - tpls_history.json
      - .github/workflows/update_content.yaml
    branches:
      - master
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' && !contains(github.event.head_commit.author.name, '[bot]')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python code
        run: |
          python .github/src/merge_encryption.py

      - name: Run python code
        run: |
          python .github/src/generate_list.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update content